# Generated by Django 3.0.5 on 2021-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210307_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbformtype',
            name='fbFormTypeId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
