# Generated by Django 3.0.5 on 2021-03-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210307_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBForm',
            fields=[
                ('FBFormId', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('FBFormLink', models.CharField(max_length=250)),
                ('FBFormTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FBFormType')),
            ],
        ),
    ]
