# Generated by Django 3.0.5 on 2021-03-10 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fbform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchId', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('branchName', models.CharField(max_length=50, unique=True)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=40)),
                ('productType', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Custmomer',
            fields=[
                ('userId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('PhoneNo', models.CharField(max_length=10)),
                ('branchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Branch')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
