# Generated by Django 3.0.5 on 2021-03-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210310_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custmomer',
            new_name='Customer',
        ),
    ]
