# Generated by Django 3.1.7 on 2021-04-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210417_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branch_products',
            new_name='branchProducts',
        ),
    ]
