# Generated by Django 3.1.7 on 2021-04-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210417_1947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branchProducts',
            new_name='branchProduct',
        ),
    ]
